# Taller de Análisis de Datos con Pandas
## Gimnasios y Entrenamiento Deportivo Fuerza y Rendimiento

In [1]:
import pandas as pd
import numpy as np

## 1. Lectura y verificación de carga

In [2]:
df_gimnasio = pd.read_csv("gimnasios_entrenamiento.csv")
print(df_gimnasio.shape)
print(list(df_gimnasio.columns))
df_gimnasio.head()

(1000, 8)
['ID_Socio', 'Sede', 'Plan', 'Disciplina_Principal', 'Visitas_Mes', 'Minutos_Promedio_Sesion', 'Gasto_Suplementos', 'Estado_Membresia']

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Anserma Norte,VIP Total,Crossfit,24,62.4,NaN,Activa
1,SOC-10465,Anserma Centro,VIP Total,Funcional,22,61.1,129000.0,Activa
2,SOC-10373,Risaralda Caldas,Platino,Yoga y Pilates,14,70.2,69000.0,Congelada
3,SOC-10731,Viterbo Centro,Estudiantil,Spinning,20,49.9,19000.0,Vencida
4,SOC-10758,Risaralda Caldas,VIP Total,Crossfit,23,35.8,NaN,Activa

In [3]:
df_gimnasio.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID_Socio                 1000 non-null   str
 1   Sede                     1000 non-null   str
 2   Plan                     1000 non-null   str
 3   Disciplina_Principal     1000 non-null   str
 4   Visitas_Mes              1000 non-null   int64
 5   Minutos_Promedio_Sesion  938 non-null    float64
 6   Gasto_Suplementos        910 non-null    float64
 7   Estado_Membresia         1000 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 62.6 KB

## 2. Selección unidimensional y multivariable

In [4]:
disciplinas = df_gimnasio["Disciplina_Principal"]
print(type(disciplinas))
disciplinas.head()

<class 'pandas.Series'>

0          Crossfit
1         Funcional
2    Yoga y Pilates
3          Spinning
4          Crossfit
Name: Disciplina_Principal, dtype: str

In [5]:
df_reducido = df_gimnasio[["Sede", "Plan", "Visitas_Mes"]]
print(type(df_reducido))
df_reducido.head()

<class 'pandas.DataFrame'>

               Sede         Plan  Visitas_Mes
0     Anserma Norte    VIP Total           24
1    Anserma Centro    VIP Total           22
2  Risaralda Caldas      Platino           14
3    Viterbo Centro  Estudiantil           20
4  Risaralda Caldas    VIP Total           23

## 3. Acceso por etiqueta con .loc[]

In [6]:
df_gimnasio.loc[350]

ID_Socio                       SOC-10553
Sede                       Anserma Norte
Plan                             Platino
Disciplina_Principal           Funcional
Visitas_Mes                           10
Minutos_Promedio_Sesion             51.9
Gasto_Suplementos                48000.0
Estado_Membresia               Congelada
Name: 350, dtype: object

## 4. Tratamiento de redundancias

In [7]:
print(df_gimnasio.duplicated().sum())
print(len(df_gimnasio))
df_gimnasio = df_gimnasio.drop_duplicates(keep="first")
print(df_gimnasio.duplicated().sum())
print(len(df_gimnasio))

15
1000
0
985

## 5. Filtrado por nivel de actividad

In [8]:
alta_frecuencia = df_gimnasio[df_gimnasio["Visitas_Mes"] > 18]
print(len(alta_frecuencia))
alta_frecuencia.head()

319

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Anserma Norte,VIP Total,Crossfit,24,62.4,NaN,Activa
1,SOC-10465,Anserma Centro,VIP Total,Funcional,22,61.1,129000.0,Activa
3,SOC-10731,Viterbo Centro,Estudiantil,Spinning,20,49.9,19000.0,Vencida
4,SOC-10758,Risaralda Caldas,VIP Total,Crossfit,23,35.8,NaN,Activa
8,SOC-10643,Anserma Centro,Platino,Crossfit,25,NaN,86000.0,Activa

## 6. Filtrado categórico con .isin()

6

In [9]:
planes_premium = df_gimnasio[df_gimnasio["Plan"].isin(["VIP Total", "Platino"])]
print(planes_premium["Plan"].value_counts())
planes_premium.head()

Plan
Platino      224
VIP Total    156
Name: count, dtype: int64

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Anserma Norte,VIP Total,Crossfit,24,62.4,NaN,Activa
1,SOC-10465,Anserma Centro,VIP Total,Funcional,22,61.1,129000.0,Activa
2,SOC-10373,Risaralda Caldas,Platino,Yoga y Pilates,14,70.2,69000.0,Congelada
4,SOC-10758,Risaralda Caldas,VIP Total,Crossfit,23,35.8,NaN,Activa
5,SOC-10358,Anserma Norte,Platino,Funcional,6,58.6,47000.0,Activa

## 7. Filtrado por intervalo con .between()

In [10]:
rango_duracion = df_gimnasio[df_gimnasio["Minutos_Promedio_Sesion"].between(45.0, 75.0)]
print(len(rango_duracion))
rango_duracion.head()

557

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Anserma Norte,VIP Total,Crossfit,24,62.4,NaN,Activa
1,SOC-10465,Anserma Centro,VIP Total,Funcional,22,61.1,129000.0,Activa
2,SOC-10373,Risaralda Caldas,Platino,Yoga y Pilates,14,70.2,69000.0,Congelada
3,SOC-10731,Viterbo Centro,Estudiantil,Spinning,20,49.9,19000.0,Vencida
5,SOC-10358,Anserma Norte,Platino,Funcional,6,58.6,47000.0,Activa

## 8. Consultas directas con .query()

In [11]:
viterbo_activos = df_gimnasio.query('Sede == "Viterbo Centro" and Estado_Membresia == "Activa"')
print(len(viterbo_activos))
viterbo_activos.head()

139

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
11,SOC-10096,Viterbo Centro,Estudiantil,Yoga y Pilates,3,59.0,26000.0,Activa
21,SOC-10399,Viterbo Centro,Básico,Musculación,8,79.1,11000.0,Activa
22,SOC-10698,Viterbo Centro,Estudiantil,Musculación,9,81.6,35000.0,Activa
25,SOC-10491,Viterbo Centro,Platino,Musculación,12,33.5,79000.0,Activa
29,SOC-10763,Viterbo Centro,VIP Total,Musculación,9,46.3,105000.0,Activa

## 9. Filtrado compuesto con métodos de texto

In [12]:
cond_sede = df_gimnasio["Sede"].str.startswith("Anserma")
cond_gasto = df_gimnasio["Gasto_Suplementos"] > 50000
anserma_gasto_alto = df_gimnasio[cond_sede & cond_gasto]
print(len(anserma_gasto_alto))
anserma_gasto_alto.head()

120

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
1,SOC-10465,Anserma Centro,VIP Total,Funcional,22,61.1,129000.0,Activa
8,SOC-10643,Anserma Centro,Platino,Crossfit,25,NaN,86000.0,Activa
12,SOC-10627,Anserma Centro,VIP Total,Crossfit,20,61.7,96000.0,Activa
18,SOC-10310,Anserma Centro,VIP Total,Spinning,17,61.9,163000.0,Vencida
30,SOC-10067,Anserma Centro,Platino,Crossfit,25,69.3,108000.0,Activa

## 10. Imputación de faltantes con .fillna()

In [13]:
print(df_gimnasio[["Minutos_Promedio_Sesion", "Gasto_Suplementos"]].isna().sum())
promedio_minutos = df_gimnasio["Minutos_Promedio_Sesion"].mean()
print(round(promedio_minutos, 2))
df_gimnasio["Minutos_Promedio_Sesion"] = df_gimnasio["Minutos_Promedio_Sesion"].fillna(promedio_minutos)
df_gimnasio["Gasto_Suplementos"] = df_gimnasio["Gasto_Suplementos"].fillna(0.0)
print(df_gimnasio[["Minutos_Promedio_Sesion", "Gasto_Suplementos"]].isna().sum())

Minutos_Promedio_Sesion    60
Gasto_Suplementos          90
dtype: int64
60.33
Minutos_Promedio_Sesion    0
Gasto_Suplementos          0
dtype: int64

## 11. Transformación condicional con .apply()

In [14]:
def clasificar_perfil(visitas):
    if visitas < 8:
        return "Esporádico"
    elif visitas <= 16:
        return "Regular"
    else:
        return "Frecuente"

df_gimnasio["Perfil_Atleta"] = df_gimnasio["Visitas_Mes"].apply(clasificar_perfil)
df_gimnasio[["Visitas_Mes", "Perfil_Atleta"]].head(10)

   Visitas_Mes Perfil_Atleta
0           24     Frecuente
1           22     Frecuente
2           14       Regular
3           20     Frecuente
4           23     Frecuente
5            6    Esporádico
6            5    Esporádico
7            3    Esporádico
8           25     Frecuente
9            9       Regular

In [15]:
df_gimnasio["Perfil_Atleta"].value_counts()

Perfil_Atleta
Frecuente     378
Regular       351
Esporádico    256
Name: count, dtype: int64

## 12. Renombrado y reordenamiento de atributos

In [16]:
df_gimnasio = df_gimnasio.rename(columns={
    "Minutos_Promedio_Sesion": "Duracion_Media",
    "Disciplina_Principal": "Deporte",
})
prioritarias = ["ID_Socio", "Perfil_Atleta"]
resto = [c for c in df_gimnasio.columns if c not in prioritarias]
df_gimnasio = df_gimnasio[prioritarias + resto]
df_gimnasio.head()

,ID_Socio,Perfil_Atleta,Sede,Plan,Deporte,Visitas_Mes,Duracion_Media,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Frecuente,Anserma Norte,VIP Total,Crossfit,24,62.4,0.0,Activa
1,SOC-10465,Frecuente,Anserma Centro,VIP Total,Funcional,22,61.1,129000.0,Activa
2,SOC-10373,Regular,Risaralda Caldas,Platino,Yoga y Pilates,14,70.2,69000.0,Congelada
3,SOC-10731,Frecuente,Viterbo Centro,Estudiantil,Spinning,20,49.9,19000.0,Vencida
4,SOC-10758,Frecuente,Risaralda Caldas,VIP Total,Crossfit,23,35.8,0.0,Activa

## 13. Agregación por centro de entrenamiento

In [17]:
resumen_sede = df_gimnasio.groupby("Sede").agg(
    Duracion_Media_Promedio=("Duracion_Media", "mean"),
    Gasto_Total=("Gasto_Suplementos", "sum"),
)
resumen_sede

                  Duracion_Media_Promedio  Gasto_Total
Sede
Anserma Centro                  61.021168   11599000.0
Anserma Norte                   60.972224    8403000.0
Belalcázar                      58.969526    5682000.0
Risaralda Caldas                58.676667    6628000.0
Viterbo Centro                  60.944023    8025000.0

## 14. Métricas de dispersión personalizadas

In [18]:
def rango(serie):
    return serie.max() - serie.min()

rango_por_plan = df_gimnasio.groupby("Plan")[["Visitas_Mes", "Duracion_Media"]].agg(rango)
rango_por_plan

             Visitas_Mes  Duracion_Media
Plan
Básico                27            94.2
Estudiantil           27            87.2
Platino               27            86.0
VIP Total             27            86.1

## 15. Agrupamiento multinivel

In [19]:
multinivel = df_gimnasio.groupby(["Sede", "Plan"]).agg(
    Visitas_Promedio=("Visitas_Mes", "mean"),
    Gasto_Total=("Gasto_Suplementos", "sum"),
)
multinivel

                              Visitas_Promedio  Gasto_Total
Sede             Plan
Anserma Centro   Básico              14.524272    2375000.0
                 Estudiantil         12.078947    1521000.0
                 Platino             13.865672    4252000.0
                 VIP Total           16.894737    3451000.0
Anserma Norte    Básico              13.088608    2135000.0
                 Estudiantil         12.522727     872000.0
                 Platino             14.421053    2419000.0
                 VIP Total           15.542857    2977000.0
Belalcázar       Básico              12.960784    1297000.0
                 Estudiantil         14.354839     598000.0
                 Platino             14.631579    2228000.0
                 VIP Total           14.521739    1559000.0
Risaralda Caldas Básico              12.912281    1240000.0
                 Estudiantil         15.696970     651000.0
                 Platino             14.052632    2283000.0
                 VIP Total           12.703704    2454000.0
Viterbo Centro   Básico              13.826667    1616000.0
                 Estudiantil         14.035714    1117000.0
                 Platino             14.674419    2448000.0
                 VIP Total           15.545455    2844000.0