# Taller de Análisis de Datos con Pandas
## Gimnasios y Entrenamiento Deportivo — Fuerza y Rendimiento

In [1]:
import pandas as pd
import numpy as np

## Creación de los datos

In [2]:
np.random.seed(2026)
n = 985

data = {
    "ID_Socio": [f"SOC-{10001 + i}" for i in range(n)],
    "Sede": np.random.choice(["Manizales Centro", "Pereira Circunvalar", "Armenia Norte", "Chinchiná", "Medellín Poblado"], n, p=[0.28, 0.22, 0.18, 0.12, 0.20]),
    "Plan": np.random.choice(["Básico", "Platino", "VIP Total", "Estudiantil"], n, p=[0.35, 0.25, 0.15, 0.25]),
    "Disciplina_Principal": np.random.choice(["Musculación", "Crossfit", "Spinning", "Yoga y Pilates", "Funcional"], n),
    "Visitas_Mes": np.random.randint(1, 29, n),
    "Minutos_Promedio_Sesion": np.random.normal(60, 18, n).clip(20, 120).round(1),
    "Gasto_Suplementos": np.random.choice([0, 15000, 20000, 25000, 35000, 45000, 60000, 75000, 90000, 120000], n).astype(float),
    "Estado_Membresia": np.random.choice(["Activa", "Congelada", "Vencida"], n, p=[0.70, 0.15, 0.15]),
}

df_base = pd.DataFrame(data)
df_base

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10001,Manizales Centro,Platino,Spinning,1,62.6,120000.0,Activa
1,SOC-10002,Pereira Circunvalar,Básico,Crossfit,25,99.2,90000.0,Vencida
2,SOC-10003,Medellín Poblado,Básico,Musculación,20,64.3,75000.0,Activa
3,SOC-10004,Manizales Centro,VIP Total,Spinning,20,54.2,35000.0,Congelada
4,SOC-10005,Pereira Circunvalar,Platino,Musculación,13,66.8,120000.0,Activa
...,...,...,...,...,...,...,...,...
980,SOC-10981,Manizales Centro,Básico,Funcional,25,88.7,20000.0,Activa
981,SOC-10982,Armenia Norte,Básico,Spinning,23,45.4,25000.0,Activa
982,SOC-10983,Manizales Centro,Estudiantil,Musculación,14,51.7,60000.0,Activa
983,SOC-10984,Medellín Poblado,Básico,Musculación,15,73.6,0.0,Activa
984,SOC-10985,Armenia Norte,Platino,Funcional,15,72.3,75000.0,Activa

In [3]:
df_base.loc[np.random.choice(n, 60, replace=False), "Minutos_Promedio_Sesion"] = np.nan
df_base.loc[np.random.choice(n, 90, replace=False), "Gasto_Suplementos"] = np.nan
df_base.isna().sum()

ID_Socio                    0
Sede                        0
Plan                        0
Disciplina_Principal        0
Visitas_Mes                 0
Minutos_Promedio_Sesion    60
Gasto_Suplementos          90
Estado_Membresia            0
dtype: int64

In [4]:
df_completo = pd.concat([df_base, df_base.sample(15, random_state=7)], ignore_index=True)
df_completo = df_completo.sample(frac=1, random_state=11).reset_index(drop=True)
df_completo.shape

(1000, 8)

In [5]:
df_completo.to_csv("gimnasios_entrenamiento.csv", index=False)

## 1. Lectura y verificación de carga

In [6]:
df_gimnasio = pd.read_csv("gimnasios_entrenamiento.csv")
df_gimnasio

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Medellín Poblado,VIP Total,Crossfit,28,48.0,90000.0,Congelada
1,SOC-10465,Pereira Circunvalar,Estudiantil,Musculación,19,41.3,15000.0,Activa
2,SOC-10373,Manizales Centro,Platino,Musculación,11,75.8,35000.0,Activa
3,SOC-10731,Manizales Centro,VIP Total,Yoga y Pilates,20,55.4,20000.0,Congelada
4,SOC-10758,Pereira Circunvalar,Básico,Crossfit,27,NaN,120000.0,Activa
...,...,...,...,...,...,...,...,...
995,SOC-10338,Medellín Poblado,VIP Total,Crossfit,1,66.0,20000.0,Activa
996,SOC-10092,Medellín Poblado,Platino,Spinning,4,63.8,75000.0,Vencida
997,SOC-10081,Manizales Centro,Básico,Crossfit,4,53.7,0.0,Activa
998,SOC-10704,Medellín Poblado,Básico,Musculación,18,46.5,120000.0,Activa
999,SOC-10922,Medellín Poblado,Platino,Crossfit,11,47.8,45000.0,Congelada

In [7]:
df_gimnasio.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID_Socio                 1000 non-null   str
 1   Sede                     1000 non-null   str
 2   Plan                     1000 non-null   str
 3   Disciplina_Principal     1000 non-null   str
 4   Visitas_Mes              1000 non-null   int64
 5   Minutos_Promedio_Sesion  938 non-null    float64
 6   Gasto_Suplementos        910 non-null    float64
 7   Estado_Membresia         1000 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 62.6 KB

## 2. Selección unidimensional y multivariable

In [8]:
disciplinas = df_gimnasio["Disciplina_Principal"]
disciplinas, type(disciplinas)

(0            Crossfit
 1         Musculación
 2         Musculación
 3      Yoga y Pilates
 4            Crossfit
             ...
 995          Crossfit
 996          Spinning
 997          Crossfit
 998       Musculación
 999          Crossfit
 Name: Disciplina_Principal, Length: 1000, dtype: str,
 pandas.Series)

In [9]:
df_reducido = df_gimnasio[["Sede", "Plan", "Visitas_Mes"]]
df_reducido

                    Sede         Plan  Visitas_Mes
0       Medellín Poblado    VIP Total           28
1    Pereira Circunvalar  Estudiantil           19
2       Manizales Centro      Platino           11
3       Manizales Centro    VIP Total           20
4    Pereira Circunvalar       Básico           27
..                   ...          ...          ...
995     Medellín Poblado    VIP Total            1
996     Medellín Poblado      Platino            4
997     Manizales Centro       Básico            4
998     Medellín Poblado       Básico           18
999     Medellín Poblado      Platino           11

[1000 rows x 3 columns]

## 3. Acceso por etiqueta con .loc[]

In [10]:
fila = df_gimnasio.loc[350]
fila

ID_Socio                        SOC-10553
Sede                            Chinchiná
Plan                              Platino
Disciplina_Principal       Yoga y Pilates
Visitas_Mes                            27
Minutos_Promedio_Sesion              79.9
Gasto_Suplementos                 60000.0
Estado_Membresia                   Activa
Name: 350, dtype: object

## 4. Tratamiento de redundancias

In [11]:
df_gimnasio.duplicated().sum()

np.int64(15)

In [12]:
df_sin_duplicados = df_gimnasio.drop_duplicates(keep="first")
df_sin_duplicados.shape

(985, 8)

## 5. Filtrado por nivel de actividad

In [13]:
alta_frecuencia = df_sin_duplicados[df_sin_duplicados["Visitas_Mes"] > 18]
alta_frecuencia

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Medellín Poblado,VIP Total,Crossfit,28,48.0,90000.0,Congelada
1,SOC-10465,Pereira Circunvalar,Estudiantil,Musculación,19,41.3,15000.0,Activa
3,SOC-10731,Manizales Centro,VIP Total,Yoga y Pilates,20,55.4,20000.0,Congelada
4,SOC-10758,Pereira Circunvalar,Básico,Crossfit,27,NaN,120000.0,Activa
7,SOC-10768,Manizales Centro,Básico,Funcional,20,37.6,0.0,Congelada
...,...,...,...,...,...,...,...,...
975,SOC-10843,Medellín Poblado,Básico,Spinning,25,83.3,90000.0,Activa
976,SOC-10898,Armenia Norte,Básico,Yoga y Pilates,20,38.9,60000.0,Activa
979,SOC-10901,Pereira Circunvalar,Estudiantil,Spinning,22,60.5,35000.0,Vencida
983,SOC-10417,Manizales Centro,Básico,Funcional,22,69.2,0.0,Activa
986,SOC-10605,Armenia Norte,Estudiantil,Spinning,22,71.2,NaN,Vencida

## 6. Filtrado categórico con .isin()

In [14]:
planes_premium = df_sin_duplicados[df_sin_duplicados["Plan"].isin(["VIP Total", "Platino"])]
planes_premium

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Medellín Poblado,VIP Total,Crossfit,28,48.0,90000.0,Congelada
2,SOC-10373,Manizales Centro,Platino,Musculación,11,75.8,35000.0,Activa
3,SOC-10731,Manizales Centro,VIP Total,Yoga y Pilates,20,55.4,20000.0,Congelada
5,SOC-10358,Chinchiná,VIP Total,Yoga y Pilates,3,24.9,25000.0,Congelada
8,SOC-10643,Medellín Poblado,Platino,Yoga y Pilates,7,49.1,0.0,Vencida
...,...,...,...,...,...,...,...,...
993,SOC-10270,Pereira Circunvalar,Platino,Spinning,17,65.1,15000.0,Activa
994,SOC-10952,Armenia Norte,VIP Total,Musculación,12,71.8,120000.0,Activa
995,SOC-10338,Medellín Poblado,VIP Total,Crossfit,1,66.0,20000.0,Activa
996,SOC-10092,Medellín Poblado,Platino,Spinning,4,63.8,75000.0,Vencida
999,SOC-10922,Medellín Poblado,Platino,Crossfit,11,47.8,45000.0,Congelada

## 7. Filtrado por intervalo con .between()

In [15]:
rango_duracion = df_sin_duplicados[df_sin_duplicados["Minutos_Promedio_Sesion"].between(45.0, 75.0)]
rango_duracion

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Medellín Poblado,VIP Total,Crossfit,28,48.0,90000.0,Congelada
3,SOC-10731,Manizales Centro,VIP Total,Yoga y Pilates,20,55.4,20000.0,Congelada
8,SOC-10643,Medellín Poblado,Platino,Yoga y Pilates,7,49.1,0.0,Vencida
9,SOC-10608,Pereira Circunvalar,VIP Total,Spinning,4,55.9,90000.0,Vencida
10,SOC-10375,Manizales Centro,VIP Total,Musculación,10,54.2,NaN,Activa
...,...,...,...,...,...,...,...,...
995,SOC-10338,Medellín Poblado,VIP Total,Crossfit,1,66.0,20000.0,Activa
996,SOC-10092,Medellín Poblado,Platino,Spinning,4,63.8,75000.0,Vencida
997,SOC-10081,Manizales Centro,Básico,Crossfit,4,53.7,0.0,Activa
998,SOC-10704,Medellín Poblado,Básico,Musculación,18,46.5,120000.0,Activa
999,SOC-10922,Medellín Poblado,Platino,Crossfit,11,47.8,45000.0,Congelada

## 8. Consultas directas con .query()

In [16]:
medellin_activos = df_sin_duplicados.query('Sede == "Medellín Poblado" and Estado_Membresia == "Activa"')
medellin_activos

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
13,SOC-10401,Medellín Poblado,VIP Total,Funcional,4,71.2,75000.0,Activa
14,SOC-10618,Medellín Poblado,Estudiantil,Crossfit,22,NaN,20000.0,Activa
21,SOC-10399,Medellín Poblado,Básico,Musculación,24,30.5,120000.0,Activa
25,SOC-10491,Medellín Poblado,Básico,Crossfit,12,61.7,120000.0,Activa
27,SOC-10523,Medellín Poblado,Básico,Spinning,5,52.8,120000.0,Activa
...,...,...,...,...,...,...,...,...
962,SOC-10371,Medellín Poblado,Estudiantil,Crossfit,18,NaN,120000.0,Activa
967,SOC-10505,Medellín Poblado,Estudiantil,Spinning,15,58.8,35000.0,Activa
975,SOC-10843,Medellín Poblado,Básico,Spinning,25,83.3,90000.0,Activa
995,SOC-10338,Medellín Poblado,VIP Total,Crossfit,1,66.0,20000.0,Activa
998,SOC-10704,Medellín Poblado,Básico,Musculación,18,46.5,120000.0,Activa

## 9. Filtrado compuesto con métodos de texto

In [17]:
filtro = (df_sin_duplicados["Sede"].str.startswith("Manizales")) & (df_sin_duplicados["Gasto_Suplementos"] > 50000)
manizales_gasto_alto = df_sin_duplicados[filtro]
manizales_gasto_alto

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
15,SOC-10642,Manizales Centro,Platino,Yoga y Pilates,14,46.1,120000.0,Activa
16,SOC-10290,Manizales Centro,Estudiantil,Musculación,8,90.3,90000.0,Activa
17,SOC-10341,Manizales Centro,Básico,Funcional,14,60.9,120000.0,Congelada
30,SOC-10067,Manizales Centro,VIP Total,Spinning,27,60.6,120000.0,Congelada
50,SOC-10204,Manizales Centro,Básico,Yoga y Pilates,7,NaN,90000.0,Activa
...,...,...,...,...,...,...,...,...
935,SOC-10840,Manizales Centro,Básico,Musculación,7,37.4,90000.0,Activa
936,SOC-10694,Manizales Centro,Platino,Crossfit,19,34.1,90000.0,Activa
939,SOC-10249,Manizales Centro,Estudiantil,Funcional,28,86.9,75000.0,Activa
966,SOC-10658,Manizales Centro,Básico,Musculación,21,66.1,90000.0,Activa
972,SOC-10232,Manizales Centro,Estudiantil,Crossfit,17,67.8,90000.0,Activa

## 10. Imputación de faltantes con .fillna()

In [18]:
df_fill = df_sin_duplicados.copy()
promedio_minutos = df_fill["Minutos_Promedio_Sesion"].mean()
df_fill["Minutos_Promedio_Sesion"] = df_fill["Minutos_Promedio_Sesion"].fillna(promedio_minutos)
df_fill["Gasto_Suplementos"] = df_fill["Gasto_Suplementos"].fillna(0.0)
df_fill.isna().sum()

ID_Socio                   0
Sede                       0
Plan                       0
Disciplina_Principal       0
Visitas_Mes                0
Minutos_Promedio_Sesion    0
Gasto_Suplementos          0
Estado_Membresia           0
dtype: int64

## 11. Transformación condicional con .apply()

In [19]:
def clasificar_perfil(visitas):
    if visitas < 8:
        return "Esporádico"
    elif visitas <= 16:
        return "Regular"
    else:
        return "Frecuente"

df_fill["Perfil_Atleta"] = df_fill["Visitas_Mes"].apply(clasificar_perfil)
df_fill[["Visitas_Mes", "Perfil_Atleta"]]

     Visitas_Mes Perfil_Atleta
0             28     Frecuente
1             19     Frecuente
2             11       Regular
3             20     Frecuente
4             27     Frecuente
..           ...           ...
995            1    Esporádico
996            4    Esporádico
997            4    Esporádico
998           18     Frecuente
999           11       Regular

[985 rows x 2 columns]

## 12. Renombrado y reordenamiento de atributos

In [20]:
df_renombrado = df_fill.rename(columns={
    "Minutos_Promedio_Sesion": "Duracion_Media",
    "Disciplina_Principal": "Deporte"
})
inicio = ["ID_Socio", "Perfil_Atleta"]
resto = [c for c in df_renombrado.columns if c not in inicio]
df_renombrado = df_renombrado[inicio + resto]
df_renombrado

,ID_Socio,Perfil_Atleta,Sede,Plan,Deporte,Visitas_Mes,Duracion_Media,Gasto_Suplementos,Estado_Membresia
0,SOC-10026,Frecuente,Medellín Poblado,VIP Total,Crossfit,28,48.000000,90000.0,Congelada
1,SOC-10465,Frecuente,Pereira Circunvalar,Estudiantil,Musculación,19,41.300000,15000.0,Activa
2,SOC-10373,Regular,Manizales Centro,Platino,Musculación,11,75.800000,35000.0,Activa
3,SOC-10731,Frecuente,Manizales Centro,VIP Total,Yoga y Pilates,20,55.400000,20000.0,Congelada
4,SOC-10758,Frecuente,Pereira Circunvalar,Básico,Crossfit,27,60.553297,120000.0,Activa
...,...,...,...,...,...,...,...,...,...
995,SOC-10338,Esporádico,Medellín Poblado,VIP Total,Crossfit,1,66.000000,20000.0,Activa
996,SOC-10092,Esporádico,Medellín Poblado,Platino,Spinning,4,63.800000,75000.0,Vencida
997,SOC-10081,Esporádico,Manizales Centro,Básico,Crossfit,4,53.700000,0.0,Activa
998,SOC-10704,Frecuente,Medellín Poblado,Básico,Musculación,18,46.500000,120000.0,Activa
999,SOC-10922,Regular,Medellín Poblado,Platino,Crossfit,11,47.800000,45000.0,Congelada

## 13. Agregación por centro de entrenamiento

In [21]:
grouped = df_renombrado.groupby("Sede")
resumen_sede = grouped.agg({
    "Duracion_Media": "mean",
    "Gasto_Suplementos": "sum"
})
resumen_sede

                     Duracion_Media  Gasto_Suplementos
Sede
Armenia Norte             63.078766          8280000.0
Chinchiná                 59.561903          5270000.0
Manizales Centro          60.601977         10580000.0
Medellín Poblado          60.552940          9560000.0
Pereira Circunvalar       58.928415          9750000.0

## 14. Métricas de dispersión personalizadas

In [22]:
def rango(serie):
    return serie.max() - serie.min()

rango_por_plan = df_renombrado.groupby("Plan")[["Visitas_Mes", "Duracion_Media"]].agg(rango)
rango_por_plan

             Visitas_Mes  Duracion_Media
Plan
Básico                27            82.2
Estudiantil           27            95.1
Platino               27            99.6
VIP Total             27            81.8

## 15. Agrupamiento multinivel

In [23]:
multinivel = df_renombrado.groupby(["Sede", "Plan"]).agg({
    "Visitas_Mes": "mean",
    "Gasto_Suplementos": "sum"
})
multinivel

                                 Visitas_Mes  Gasto_Suplementos
Sede                Plan
Armenia Norte       Básico         14.653846          2155000.0
                    Estudiantil    12.549020          2295000.0
                    Platino        15.460000          2395000.0
                    VIP Total      12.354839          1435000.0
Chinchiná           Básico         13.425532          2375000.0
                    Estudiantil    14.041667           855000.0
                    Platino        14.700000          1205000.0
                    VIP Total      11.777778           835000.0
Manizales Centro    Básico         15.049383          3500000.0
                    Estudiantil    17.306452          2980000.0
                    Platino        14.072464          2645000.0
                    VIP Total      16.113636          1455000.0
Medellín Poblado    Básico         16.567164          3670000.0
                    Estudiantil    15.345455          2515000.0
                    Platino        13.352941          2000000.0
                    VIP Total      16.312500          1375000.0
Pereira Circunvalar Básico         14.626667          3115000.0
                    Estudiantil    14.150943          2300000.0
                    Platino        15.303571          2705000.0
                    VIP Total      15.567568          1630000.0